const db = require('../models/db');

// Nutrition is optional. Empty fields remain NULL and are shown as unavailable.
function nutritionPayload(body){
  const numeric=['calories','protein','carbohydrates','fat','fiber','sugar','sodium','health_score'];
  const values={};
  for(const field of numeric){if(body[field]!==undefined&&body[field]!==''){const value=Number(body[field]);if(!Number.isFinite(value)||value<0)return {error:field+' must be a non-negative number.'};values[field]=value}}
  if(values.health_score!==undefined&&values.health_score>100)return {error:'Health score must be between 0 and 100.'};
  if(body.spice_level&& !['Mild','Medium','Hot'].includes(body.spice_level))return {error:'Invalid spice level.'};
  values.spice_level=body.spice_level||null;values.is_vegetarian=body.is_vegetarian===undefined?null:['true','1',true,1].includes(body.is_vegetarian)?1:0;values.nutrition_verified=body.nutrition_verified===undefined?null:['true','1',true,1].includes(body.nutrition_verified)?1:0;return {values};
}
exports.list = async (req,res,next) => { try { const { search='', category='' } = req.query; const [rows] = await db.execute(`SELECT f.*, c.category_name FROM food_items f JOIN categories c ON f.category_id=c.id WHERE f.availability=1 AND f.name LIKE ? ${category ? 'AND f.category_id=?' : ''} ORDER BY f.id DESC`, category ? [`%${search}%`, category] : [`%${search}%`]); res.json(rows); } catch(e){next(e)} };
exports.getOne = async (req,res,next) => { try { const [r] = await db.execute('SELECT f.*,c.category_name FROM food_items f JOIN categories c ON f.category_id=c.id WHERE f.id=?',[req.params.id]); if(!r.length)return res.status(404).json({message:'Food item not found.'}); res.json(r[0]); }catch(e){next(e)} };
exports.create = async (req,res,next) => { try { const {name,description='',price,category_id,availability=1}=req.body; const nutrition=nutritionPayload(req.body); if(nutrition.error)return res.status(400).json({message:nutrition.error}); if(!name || Number(price)<0 || !category_id)return res.status(400).json({message:'Name, valid price and category are required.'}); const n=nutrition.values,image=req.file ? `/uploads/${req.file.filename}` : null; const [r]=await db.execute('INSERT INTO food_items(name,description,price,image,category_id,availability,calories,protein,carbohydrates,fat,fiber,sugar,sodium,spice_level,health_score,is_vegetarian,nutrition_verified) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)',[name,description,price,image,category_id,availability,n.calories??null,n.protein??null,n.carbohydrates??null,n.fat??null,n.fiber??null,n.sugar??null,n.sodium??null,n.spice_level,n.health_score??null,n.is_vegetarian??1,n.nutrition_verified??0]); res.status(201).json({message:'Food item added.',id:r.insertId}); }catch(e){next(e)} };
exports.update = async (req,res,next) => { try { const {name,description='',price,category_id,availability=1}=req.body; const nutrition=nutritionPayload(req.body); if(nutrition.error)return res.status(400).json({message:nutrition.error}); const n=nutrition.values,image=req.file ? `/uploads/${req.file.filename}` : req.body.image || null; await db.execute('UPDATE food_items SET name=?,description=?,price=?,image=?,category_id=?,availability=?,calories=COALESCE(?,calories),protein=COALESCE(?,protein),carbohydrates=COALESCE(?,carbohydrates),fat=COALESCE(?,fat),fiber=COALESCE(?,fiber),sugar=COALESCE(?,sugar),sodium=COALESCE(?,sodium),spice_level=COALESCE(?,spice_level),health_score=COALESCE(?,health_score),is_vegetarian=COALESCE(?,is_vegetarian),nutrition_verified=COALESCE(?,nutrition_verified) WHERE id=?',[name,description,price,image,category_id,availability,n.calories??null,n.protein??null,n.carbohydrates??null,n.fat??null,n.fiber??null,n.sugar??null,n.sodium??null,n.spice_level,n.health_score??null,n.is_vegetarian,n.nutrition_verified,req.params.id]); res.json({message:'Food item updated.'}); }catch(e){next(e)} };
exports.remove = async (req,res,next) => { try { const [r]=await db.execute('DELETE FROM food_items WHERE id=?',[req.params.id]); if(!r.affectedRows)return res.status(404).json({message:'Food item not found.'}); res.json({message:'Food item deleted.'}); }catch(e){next(e)} };
