const db=require('../models/db');
const PDFDocument=require('pdfkit');
const methods=['Cash on Delivery','UPI Demo','Card Demo'];
const money=value=>'₹'+new Intl.NumberFormat('en-IN',{minimumFractionDigits:2}).format(Number(value||0));

// Totals are always calculated from database food prices, never from the browser.
exports.place=async(req,res,next)=>{let conn;try{const paymentMethod=methods.includes(req.body.payment_method)?req.body.payment_method:'Cash on Delivery';conn=await db.getConnection();await conn.beginTransaction();const[addressRows]=await conn.execute('SELECT address FROM users WHERE id=?',[req.user.id]);const address=req.body.delivery_address||addressRows[0].address;if(!address?.trim()){await conn.rollback();return res.status(400).json({message:'A delivery address is required.'})}const[items]=await conn.execute('SELECT c.food_id,c.quantity,f.price FROM cart c JOIN food_items f ON f.id=c.food_id WHERE c.user_id=? AND f.availability=1',[req.user.id]);if(!items.length){await conn.rollback();return res.status(400).json({message:'Your cart is empty.'})}const total=items.reduce((sum,item)=>sum+Number(item.price)*item.quantity,0);const[o]=await conn.execute('INSERT INTO orders(user_id,total_amount,delivery_address,payment_method,payment_status) VALUES(?,?,?,?,?)',[req.user.id,total,address,paymentMethod,'Pending']);for(const item of items)await conn.execute('INSERT INTO order_items(order_id,food_id,quantity,price) VALUES(?,?,?,?)',[o.insertId,item.food_id,item.quantity,item.price]);await conn.execute('DELETE FROM cart WHERE user_id=?',[req.user.id]);await conn.commit();res.status(201).json({message:'Order placed successfully.',order_id:o.insertId,total_amount:total,payment_method:paymentMethod,payment_status:'Pending'})}catch(error){if(conn)await conn.rollback();next(error)}finally{if(conn)conn.release()}};
exports.list=async(req,res,next)=>{try{const[r]=await db.execute('SELECT * FROM orders WHERE user_id=? ORDER BY order_date DESC',[req.user.id]);res.json(r)}catch(error){next(error)}};
exports.getOne=async(req,res,next)=>{try{const[o]=await db.execute('SELECT * FROM orders WHERE id=? AND user_id=?',[req.params.id,req.user.id]);if(!o.length)return res.status(404).json({message:'Order not found.'});const[i]=await db.execute('SELECT oi.*,f.name,f.image FROM order_items oi JOIN food_items f ON f.id=oi.food_id WHERE oi.order_id=?',[req.params.id]);res.json({...o[0],items:i})}catch(error){next(error)}};
exports.updateStatus=async(req,res,next)=>{try{const allowed=['Pending','Preparing','Out for Delivery','Delivered','Cancelled'];if(!allowed.includes(req.body.status))return res.status(400).json({message:'Invalid order status.'});await db.execute('UPDATE orders SET status=? WHERE id=?',[req.body.status,req.params.id]);res.json({message:'Order status updated.'})}catch(error){next(error)}};
// Invoice ownership is verified here on the server, not only in the browser.
exports.invoice=async(req,res,next)=>{try{const[rows]=await db.execute('SELECT o.*,u.name,u.email FROM orders o JOIN users u ON u.id=o.user_id WHERE o.id=?',[req.params.id]);const order=rows[0];if(!order)return res.status(404).json({message:'Order not found.'});if(req.user.role!=='admin'&&Number(order.user_id)!==Number(req.user.id))return res.status(403).json({message:'You cannot download this invoice.'});const[items]=await db.execute('SELECT oi.quantity,oi.price,f.name FROM order_items oi JOIN food_items f ON f.id=oi.food_id WHERE oi.order_id=?',[order.id]);const doc=new PDFDocument({size:'A4',margin:48});res.setHeader('Content-Type','application/pdf');res.setHeader('Content-Disposition','attachment; filename="FlavorHub-Invoice-'+order.id+'.pdf"');doc.pipe(res);doc.fillColor('#0d1b2a').fontSize(24).text('FlavorHub');doc.fillColor('#333').fontSize(15).text('Food Order Invoice');doc.moveDown().fontSize(10).text('Invoice: FH-INV-'+new Date(order.order_date).getFullYear()+'-'+String(order.id).padStart(6,'0'));doc.text('Order ID: #'+order.id);doc.text('Order date: '+new Date(order.order_date).toLocaleString('en-IN'));doc.moveDown().fontSize(12).text('Customer Details');doc.fontSize(10).text(order.name);doc.text(order.email);doc.text('Delivery address: '+order.delivery_address);doc.moveDown().fontSize(12).text('Items');doc.moveDown(.4).fontSize(10);items.forEach(item=>{doc.text(item.name+' x '+item.quantity,50,doc.y,{continued:true});doc.text(money(item.price)+' each | '+money(Number(item.price)*item.quantity),{align:'right'})});doc.moveDown().fontSize(12).text('Grand Total: '+money(order.total_amount),{align:'right'});doc.fontSize(10).text('Payment method: '+(order.payment_method||'Cash on Delivery'),{align:'right'});doc.text('Payment status: '+(order.payment_status||'Pending'),{align:'right'});doc.text('Order status: '+order.status,{align:'right'});doc.moveDown(3).fillColor('#666').fontSize(9).text('Thank you for ordering from FlavorHub. This invoice was generated electronically.',{align:'center'});doc.end()}catch(error){next(error)}};
